export default {
  theme: 'light',
  user: {},
  cart: { size: 0, products: [], recipes: []},
  wishList: { size: 0, products: [], recipes: []},
  products: [
    {
      id: '2A',
      name: 'producto 2',
      cost: 35,
      price: 40,
      provider: '',
      barcode: 22345678,
      stock: 11,
      discount: 5,
      description: 'description',
      picture: '',
      unitSales: 2,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '3A',
      name: 'producto 3',
      cost: 85,
      price: 90,
      provider: '',
      barcode: 13345678,
      stock: 40,
      discount: 15,
      description: 'description',
      picture: '',
      unitSales: 3,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '4A',
      name: 'producto 4',
      cost: 95,
      price: 120,
      provider: '',
      barcode: 12345688,
      stock: 12,
      discount: 10,
      description: 'description',
      picture: '',
      unitSales: 5,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '5A',
      name: 'producto 5',
      cost: 48,
      price: 52,
      provider: '',
      barcode: 32345678,
      stock: 14,
      discount: 5,
      description: 'description',
      picture: '',
      unitSales: 8,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '6A',
      name: 'producto 6',
      cost: 85,
      price: 100,
      provider: '',
      barcode: 892345678,
      stock: 12,
      discount: 5,
      description: 'description',
      picture: '',
      unitSales: 1,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '7A',
      name: 'producto 7',
      cost: 65,
      price: 90,
      provider: '',
      barcode: 72345678,
      stock: 2,
      discount: 20,
      description: 'description',
      picture: '',
      unitSales: 2,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '8A',
      name: 'producto 8',
      cost: 150,
      price: 200,
      provider: '',
      barcode: 92345679,
      stock: 3,
      discount: 0,
      description: 'description',
      picture: '',
      unitSales: 2,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '9A',
      name: 'producto 9',
      cost: 5,
      price: 10,
      provider: '',
      barcode: 44445678,
      stock: 100,
      discount: 0,
      description: 'description',
      picture: '',
      unitSales: 10,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '1B',
      name: 'producto 10',
      cost: 15,
      price: 20,
      provider: '',
      barcode: 33345678,
      stock: 10,
      discount: 0,
      description: 'description',
      picture: '',
      unitSales: 6,
      comment: 'comment',
      unit: 'unit',
    },
    {
      id: '2B',
      name: 'producto 11',
      cost: 47,
      price: 60,
      provider: '',
      barcode: 22342678,
      stock: 12,
      discount: 10,
      description: 'description',
      picture: '',
      unitSales: 5,
      comment: 'comment',
      unit: 'unit',
    },
  ],
  recipes: [
    {
      id: 'R1',
      description: 'description',
      name: 'Receta 1',
      video: 'url',
      utensils: 'Utensils',
      country: 'Argentina',
      time: '20m',
      likes: 10,
      people: 3,
    },
    {
      id: 'R2',
      description: 'description',
      name: 'Receta 2',
      video: 'url',
      utensils: 'Utensils',
      country: 'Peru',
      time: '30m',
      likes: 15,
      people: 4,
    },
    {
      id: 'R3',
      description: 'description',
      name: 'Receta 3',
      video: 'url',
      utensils: 'Utensils',
      country: 'Colombia',
      time: '1h',
      likes: 8,
      people: 8,
    },
    {
      id: 'R4',
      description: 'description',
      name: 'Receta 4',
      video: 'url',
      utensils: 'Utensils',
      country: 'Mexico',
      time: '30m',
      likes: 20,
      people: 4,
    },
    {
      id: 'R5',
      description: 'description',
      name: 'Receta 5',
      video: 'url',
      utensils: 'Utensils',
      country: 'Brasil',
      time: '40m',
      likes: 15,
      people: 4,
    },
    {
      id: 'R6',
      description: 'description',
      name: 'Receta 6',
      video: 'url',
      utensils: 'Utensils',
      country: 'Chile',
      time: '1h',
      likes: 2,
      people: 6,
    },
    {
      id: 'R7',
      description: 'description',
      name: 'Receta 7',
      video: 'url',
      utensils: 'Utensils',
      country: 'Venezuela',
      time: '35m',
      likes: 20,
      people: 6,
    },
    {
      id: 'R8',
      description: 'description',
      name: 'Receta 8',
      video: 'url',
      utensils: 'Utensils',
      country: 'Urugay',
      time: '10m',
      likes: 40,
      people: 1,
    },
    {
      id: 'R9',
      description: 'description',
      name: 'Receta 9',
      video: 'url',
      utensils: 'Utensils',
      country: 'Ecuador',
      time: '20m',
      likes: 1,
      people: 4,
    },
    {
      id: 'R10',
      description: 'description',
      name: 'Receta 10',
      video: 'url',
      utensils: 'Utensils',
      country: 'Costa Rica',
      time: '32m',
      likes: 14,
      people: 5,
    },
  ],
};
